---
title: "Codebook"
author: "Tony"
date: "12/07/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Peer-graded Assignment: Getting and Cleaning Data Course Project
This dataset is organized from the following data that was collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the following website:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

There are mainly five steps:

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

There are totally 89 variables and 180 instances. 

Subject: Code of the participants.
Activity: Different activities that participants took part in. There were six activities. 
Label: Label of different activities. No.1-6.
Other variables are different measurements. 

R vision: 4.0.1
